name: Java CI Pipeline

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Cache Maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-modules
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and Test
        run: mvn -B -U clean package -s settings.xml -Dimage=ghcr.io/andidroid/testhollowjar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: testhollowjar-artifact
          path: target/testhollowjar.jar
      - name: Set up JDK 11 for deploy to GitHub Container Registry
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "11"
          server-id: ghcr.io
          settings-path: ${{ github.workspace }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Container Registry
        run: mvn com.google.cloud.tools:jib-maven-plugin:3.1.4:build -Dimage=ghcr.io/andidroid/testhollowjar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ghcr.io/andidroid/testhollowjar
          fail-build: false
          sarif: sarif.txt
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: sarif.txt
          path: sarif.txt
